### ISSUE TITLE
The 'pythonx' dir needs to contain an __init__.py

### ISSUE THREAD

**Issue by magnetophon** [guyzmo/notmuch-abook#31]
I don't know anything about python, but when I was trying to package this for NixOS, I got the above remark on IRC.

**Comment by guyzmo** [comment]
I'm sorry for letting this slide, but I definitely need to have a look.

**Comment by guyzmo** [comment]
This should be fixed now in the sources. Please reopen in case it's still broken. BTW, even though this module can work as a python module (and I guess this is why you had the issue, as in the `setup.py` I set up the `pythonx` directory to be the package) it would be a better idea to package it as a vim plugin.

**Comment by magnetophon** [comment]
Thanks for the fix.
Unfortunately, my package still doesn't run, though I don't know if that's because of my pkg, your program, or just because NixOS is weird ;)

This is the error I get:

```
$ notmuch_abook
Traceback (most recent call last):
  File "/nix/store/vqw189002x4xysijb0jqhxxllnmpdk8r-notmuch-abook-git-2016-03-12/bin/.notmuch_abook-wrapped", line 10, in <module>
    load_entry_point('notmuch-abook==1.7', 'console_scripts', 'notmuch_abook')()
  File "/nix/store/lzzdlwam8hqdpbpiagiq4kiks33dmsyv-python2.7-setuptools-18.2/lib/python2.7/site-packages/setuptools-18.2-py2.7.egg/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/nix/store/lzzdlwam8hqdpbpiagiq4kiks33dmsyv-python2.7-setuptools-18.2/lib/python2.7/site-packages/setuptools-18.2-py2.7.egg/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/nix/store/lzzdlwam8hqdpbpiagiq4kiks33dmsyv-python2.7-setuptools-18.2/lib/python2.7/site-packages/setuptools-18.2-py2.7.egg/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/nix/store/lzzdlwam8hqdpbpiagiq4kiks33dmsyv-python2.7-setuptools-18.2/lib/python2.7/site-packages/setuptools-18.2-py2.7.egg/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/nix/store/vqw189002x4xysijb0jqhxxllnmpdk8r-notmuch-abook-git-2016-03-12/lib/python2.7/site-packages/notmuch_abook/notmuch_abook.py", line 76, in <module>
    import notmuch
ImportError: No module named notmuch
```
