### ISSUE TITLE
AttributeError: 'module' object has no attribute 'NotMuchConfig'

### ISSUE THREAD

**Issue by carldavis** [guyzmo/notmuch-abook#37]
I get the following error when opening a new message with mutt using vim as my editor. Could someone provide some guidance on how to track down and resolve this error? I installed notmuch-abook via Vundle and then performed the ```python setup.py install``` step.

```
Error detected while processing function InitAddressBook:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'NotMuchConfig'
line    4:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cfg' is not defined
```

**Comment by guyzmo** [comment]
it might be possible that notmuch's python library has updated and its API is not anymore compatible with notmuch-abook anymore :-/

it's been on my todo list for a while to update notmuch-abook to the latest version, and actually use the great new feature of notmuch that can search for addresses, instead of using an SQLite database.
